
/**
 * File generated by Quickdraw on 7/12/2022.
 * 
 * Do not edit this file.
 * 
 */

import home from "@app/pages/home.tsx";
import error from "@app/pages/error.tsx";
import contact from "@app/pages/contact.tsx";
import about from "@app/pages/about.tsx";
import type { Routes } from "quickdraw/client";
const routes: Routes = {"/about":{"name":"about","path":"/about","js":"<script src=\"/assets/global.js\"></script>","importPath":"@app/pages/about.tsx"},"/contact":{"name":"contact","path":"/contact","js":"<script src=\"/assets/global.js\"></script>","importPath":"@app/pages/contact.tsx"},"/error":{"name":"error","path":"/error","js":"<script src=\"/assets/global.js\"></script>","importPath":"@app/pages/error.tsx"},"/":{"name":"home","path":"/","js":"<script src=\"/assets/global.js\"></script>","importPath":"@app/pages/home.tsx"}};
routes["/about"].Component = about;
routes["/contact"].Component = contact;
routes["/error"].Component = error;
routes["/"].Component = home;

export default routes;
