
/**
 * File generated by Quickdraw on 7/12/2022.
 * 
 * Do not edit this file.
 * 
 */

import Handler2 from "@app/api/names/random.ts"
import Handler1 from "@app/api/hello/world.ts"
import Handler0 from "@app/api/goodbye/world.ts"
import type { APIHandler } from "quickdraw";
const routes: Record<string, APIHandler> = {};
routes["/api/goodbye/world"] = Handler0;
routes["/api/hello/world"] = Handler1;
routes["/api/names/random"] = Handler2;
export default routes;
