const CODEGEN_HEADER = `
/**
 * File generated by Quickdraw on ${new Date().toLocaleDateString()}.
 * 
 * Do not edit this file.
 * 
 */\n
`;

export class Template {
  tpl: string;
  constructor() {
    this.tpl = "";
  }

  append(line: string) {
    this.tpl += line + "\n";
  }

  prepend(line: string) {
    this.tpl = line + "\n" + this.tpl;
  }

  get() {
    return CODEGEN_HEADER + this.tpl;
  }
}
